//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WebFresher042023.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProviderVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProviderVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WebFresher042023.Core.Resources.ProviderVN", typeof(ProviderVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhà cung cấp đã tồn tại trong hệ thống.
        /// </summary>
        public static string ErrorLogic_Exist_ProviderCode {
            get {
                return ResourceManager.GetString("ErrorLogic_Exist_ProviderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ tối đa 255 kí tự.
        /// </summary>
        public static string Validate_MaxLength_Address {
            get {
                return ResourceManager.GetString("Validate_MaxLength_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên tối đa 36 kí tự.
        /// </summary>
        public static string Validate_MaxLength_EmployeeId {
            get {
                return ResourceManager.GetString("Validate_MaxLength_EmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại tối đa 50 kí tự.
        /// </summary>
        public static string Validate_MaxLength_PhoneNumber {
            get {
                return ResourceManager.GetString("Validate_MaxLength_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhà cung cấp tối đa 20 kí tự.
        /// </summary>
        public static string Validate_MaxLength_ProviderCode {
            get {
                return ResourceManager.GetString("Validate_MaxLength_ProviderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà cung cấp tối đa 255 kí tự.
        /// </summary>
        public static string Validate_MaxLength_ProviderName {
            get {
                return ResourceManager.GetString("Validate_MaxLength_ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế tối đa 20 kí tự.
        /// </summary>
        public static string Validate_MaxLength_TaxCode {
            get {
                return ResourceManager.GetString("Validate_MaxLength_TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website tối đa 255 kí tự.
        /// </summary>
        public static string Validate_MaxLength_Website {
            get {
                return ResourceManager.GetString("Validate_MaxLength_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhà cung cấp không được để trống.
        /// </summary>
        public static string Validate_NotNull_ProviderCode {
            get {
                return ResourceManager.GetString("Validate_NotNull_ProviderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà cung cấp không được để trống.
        /// </summary>
        public static string Validate_NotNull_ProviderName {
            get {
                return ResourceManager.GetString("Validate_NotNull_ProviderName", resourceCulture);
            }
        }
    }
}
